### ISSUE TITLE
MacOS doesn't start after installing it 

### ISSUE THREAD

**Issue by Youseffo13** [gajjartejas/Lenovo-Ideapad-3-15IML05-Hackintosh#5]
**Describe the bug**
After I install the operating system it doesn't start anymore 

**Software Info**
 macOS Version: sonoma
 OpenCore version: 0.95
 List of kexts: those of the downloaded EFI 

**Hardware Info**
 Your laptop model : IdeaPad 3 15IML05 type 81WB
 Processor: i3 10110U

**Comment by gajjartejas** [comment]
Could you please provide a detailed report?
